function [logprior]=calculate_prior(param_col,prior)

    logprior = log_truncatednormal(param_col(1,1),prior.rho_mean,prior.rho_std,0,1)+...
      log_truncatednormal(param_col(1,2),prior.rho_mean,prior.rho_std,0,1)+log_truncatednormal(param_col(1,3),prior.rho_mean,prior.rho_std,0,1)+...
      log(gampdf(param_col(1,4),prior.gamma_a,1/prior.gamma_b))+log(gampdf(param_col(1,5),prior.gamma_a,1/prior.gamma_b))+...
      log(gampdf(param_col(1,6),prior.gamma_a,1/prior.gamma_b))+log(gampdf(param_col(1,7),prior.gamma_a,1/prior.gamma_b))+...
      log(gampdf(param_col(1,8),prior.gamma_a,1/prior.gamma_b))+...
      log(gampdf(param_col(1,9),prior.gamma_a,1/prior.gamma_b))+log(gampdf(param_col(1,10),prior.gamma_a,1/prior.gamma_b))+...
      log(gampdf(param_col(1,11),prior.gamma_a,1/prior.gamma_b))+log(gampdf(param_col(1,12),prior.gamma_a,1/prior.gamma_b))+...
      log(gampdf(param_col(1,13),prior.gamma_a,1/prior.gamma_b))+...
      log(normpdf(param_col(1,14),prior.gammag_1,prior.gammag_2))+log(normpdf(param_col(1,15),prior.gammapi_1,prior.gammapi_2))+...
      log(normpdf(param_col(1,16),prior.gammax_1,prior.gammax_2))+...
      log_truncatednormal(param_col(1,17),prior.gamma_1,prior.gamma_2,0,1)+log(gampdf(param_col(1,18),prior.sigmaa_1,1/prior.sigmaa_2))+...
      log(normpdf(param_col(1,19),prior.psip_1,prior.psip_2))+log(normpdf(param_col(1,20),prior.psiw_1,prior.psiw_2))+...
      log(gampdf(param_col(1,21),prior.psiI_1,1/prior.psiI_2))+log(gampdf(param_col(1,22),prior.sigmaL_1,1/prior.sigmaL_2))+...
      log_truncatednormal(param_col(1,23),prior.a_1,prior.a_2,0,1)+log_truncatednormal(param_col(1,24),prior.aw_1,prior.aw_2,0,1)+...
      log(gampdf(param_col(1,25),prior.BETAEST_1,1/prior.BETAEST_2))+log(normpdf(param_col(1,26),prior.Gzest_1,prior.Gzest_2))+...
      log(normpdf(param_col(1,27),prior.pibarest_1,prior.pibarest_2))+log(normpdf(param_col(1,28),prior.alpha_1,prior.alpha_2));








end