%calculate covariance matrix
%measurement error estimated
burn = 40000;

load('ParPMMH_appr1_medianN100S100mediumScale_DataReal_disturbance.mat');
theta=[logit_inverse(Post.rhoR(burn:end)),logit_inverse(Post.rhog(burn:end)),logit_inverse(Post.rhomu(burn:end)),log(Post.sigma_gest(burn:end)),...
        log(Post.sigma_muest(burn:end)),log(Post.sigma_etaest(burn:end)),log(Post.sigma_zest(burn:end)),log(Post.sigma_rest(burn:end)),...
        log(100*Post.sigma_measure1(burn:end)),log(100*Post.sigma_measure2(burn:end)),log(100*Post.sigma_measure3(burn:end)),log(100*Post.sigma_measure4(burn:end)),...
        log(100*Post.sigma_measure5(burn:end)),Post.gammag(burn:end),Post.gammapi(burn:end),Post.gammax(burn:end),...
        logit_inverse(Post.gamma(burn:end)),log(Post.sigmaa(burn:end)),...
        (Post.psip(burn:end)./100),(Post.psiw(burn:end)./1000),log(Post.psiI(burn:end)),log(Post.sigmaL(burn:end)),...
        logit_inverse(Post.param_aest(burn:end)),logit_inverse(Post.param_awest(burn:end)),...
        log(Post.BETA_EST(burn:end)),Post.Gzest(burn:end),Post.pibar_est(burn:end),Post.alpha(burn:end)]; 
covmat_theta = cov(theta);
save('cov_medscale.mat','covmat_theta');






burn=20000;
load('ParPMMH_appr1_medianN200S250mediumScale_DataReal_disturbance01.mat');
theta=[logit_inverse(Post.rhoR(burn:end)),logit_inverse(Post.rhog(burn:end)),logit_inverse(Post.rhomu(burn:end)),log(Post.sigma_gest(burn:end)),...
        log(Post.sigma_muest(burn:end)),log(Post.sigma_etaest(burn:end)),log(Post.sigma_zest(burn:end)),log(Post.sigma_rest(burn:end)),...
        Post.gammag(burn:end),Post.gammapi(burn:end),Post.gammax(burn:end),logit_inverse(Post.gamma(burn:end)),log(Post.sigmaa(burn:end)),...
        (Post.psip(burn:end)./100),(Post.psiw(burn:end)./1000),log(Post.psiI(burn:end)),log(Post.sigmaL(burn:end)),...
        logit_inverse(Post.param_aest(burn:end)),logit_inverse(Post.param_awest(burn:end)),...
        log(Post.BETA_EST(burn:end)),Post.Gzest(burn:end),Post.pibar_est(burn:end),Post.alpha(burn:end)]; 
covmat_theta = cov(theta);
save('cov_medscale_fixedmea01.mat','covmat_theta');


burn = 120000;

load('ParPMMH_appr1_medianN100S250mediumScale_DataReal_disturbance025_SW.mat');
theta=[logit_inverse(Post.rhoR(burn:end)),logit_inverse(Post.rhog(burn:end)),logit_inverse(Post.rhomu(burn:end)),log(Post.sigma_gest(burn:end)),...
        log(Post.sigma_muest(burn:end)),log(Post.sigma_etaest(burn:end)),log(Post.sigma_zest(burn:end)),log(Post.sigma_rest(burn:end)),...
        Post.gammag(burn:end),Post.gammapi(burn:end),Post.gammax(burn:end),logit_inverse(Post.gamma(burn:end)),log(Post.sigmaa(burn:end)),...
        (Post.psip(burn:end)./100),(Post.psiw(burn:end)./1000),log(Post.psiI(burn:end)),log(Post.sigmaL(burn:end)),...
        logit_inverse(Post.param_aest(burn:end)),logit_inverse(Post.param_awest(burn:end)),...
        log(Post.BETA_EST(burn:end)),Post.Gzest(burn:end),Post.pibar_est(burn:end),Post.alpha(burn:end)]; 

covmat_theta = cov(theta);
save('cov_medscale_SW.mat','covmat_theta');