figure
subplot(6,4,1);plot(Post.rhoR,'LineWidth',2);
subplot(6,4,2);plot(Post.rhog,'LineWidth',2);
subplot(6,4,3);plot(Post.rhomu,'LineWidth',2);
subplot(6,4,4);plot(Post.sigma_gest,'LineWidth',2);
subplot(6,4,5);plot(Post.sigma_muest,'LineWidth',2);
subplot(6,4,6);plot(Post.sigma_etaest,'LineWidth',2);
subplot(6,4,7);plot(Post.sigma_zest,'LineWidth',2);
subplot(6,4,8);plot(Post.sigma_rest,'LineWidth',2);
subplot(6,4,9);plot(Post.gammag,'LineWidth',2);
subplot(6,4,10);plot(Post.gammapi,'LineWidth',2);
subplot(6,4,11);plot(Post.gammax,'LineWidth',2);
subplot(6,4,12);plot(Post.gamma,'LineWidth',2);
subplot(6,4,13);plot(Post.sigmaa,'LineWidth',2);
subplot(6,4,14);plot(Post.psip,'LineWidth',2);
subplot(6,4,15);plot(Post.psiw,'LineWidth',2);
subplot(6,4,16);plot(Post.psiI,'LineWidth',2);
subplot(6,4,17);plot(Post.sigmaL,'LineWidth',2);
subplot(6,4,18);plot(Post.param_aest,'LineWidth',2);
subplot(6,4,19);plot(Post.param_awest,'LineWidth',2);
subplot(6,4,20);plot(Post.BETA_EST,'LineWidth',2);
subplot(6,4,21);plot(Post.Gzest,'LineWidth',2);
subplot(6,4,22);plot(Post.pibar_est,'LineWidth',2);
subplot(6,4,23);plot(Post.alpha,'LineWidth',2);

