function [logprior]=calculate_prior(param_col,prior)

    logprior = log_truncatednormal(param_col(1,1),prior.tau_mean,prior.tau_std,0,inf)+...
      log_truncatednormal(param_col(2,1),prior.psi1_mean,prior.psi1_std,0,inf)+...
      log_truncatednormal(param_col(3,1),prior.psi2_mean,prior.psi2_std,0,inf)+...
      log_truncatednormal(param_col(4,1),prior.rhoR_mean,prior.rhoR_std,0,1)+...
      log_truncatednormal(param_col(5,1),prior.rhog_mean,prior.rhog_std,0,1)+...
      log_truncatednormal(param_col(6,1),prior.rhoz_mean,prior.rhoz_std,0,1)+...
      log_IG_PDF_used(param_col(7,1),prior.sigma_v0/2,prior.sigma_s0/2)+log_IG_PDF_used(param_col(8,1),prior.sigma_v0/2,prior.sigma_s0/2)+...
      log_IG_PDF_used(param_col(9,1),prior.sigma_v0/2,prior.sigma_s0/2)+...
      log_truncatednormal(param_col(10,1),prior.rA_mean,prior.rA_std,0,inf)+...
      log_truncatednormal(param_col(11,1),prior.piA_mean,prior.piA_std,0,inf)+...
      log(normpdf(param_col(12,1),prior.gammaQ_mean,prior.gammaQ_std))+...
      log_truncatednormal(param_col(13,1),prior.sigma_measure_mean,prior.sigma_measure_std,0,inf)+...
      log_truncatednormal(param_col(14,1),prior.sigma_measure_mean,prior.sigma_measure_std,0,inf)+...
      log_truncatednormal(param_col(15,1),prior.sigma_measure_mean,prior.sigma_measure_std,0,inf);







end